services:

  database:
    image: mysql:8.4.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'eu-talent'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: Europe/Berlin
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_network

  backend:
    build:
      context: ../
      dockerfile: docker/backend.Dockerfile
    container_name: backend
    volumes:
      - ./assets:/app/DataDomain/assets
      - ../backend:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - backend_network

#  frontend:
#    build:
#      context: ../
#      dockerfile: docker/frontend.Dockerfile
#    container_name: frontend
#    volumes:
#      - ./assets:/usr/share/nginx/html/assets
#      - ../frontend:/usr/share/nginx/html
#    ports:
#      - "80:80"
#      - "443:443"
#    networks:
#      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  db_data: {}
