openapi: 3.0.0
info:
  title: EU Talent API
  version: 1.0.0
paths:
  /api/login:
    post:
      summary: Login user
      operationId: authenticateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticateUserRequestBody'

      responses:
        '200':
          description: OK

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '500':
          description: Internal Server Error

components:
  schemas:
    AuthenticateUserRequestBody:
      type: object
      required:
        - password
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
