openapi: 3.0.0
info:
  title: EU Talent API
  version: 1.0.0
paths:
  /api/create-user:
    post:
      summary: Create a user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequestBody'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponseBody'

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '500':
          description: Internal Server Error

components:
  schemas:
    CreateUserRequestBody:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string

    CreateUserResponseBody:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOifghjkgfdsfghj
