openapi: 3.0.0
info:
  title: EU Talent API
  version: 1.0.0
paths:
  /api/create-message:
    post:
      summary: Create a message
      operationId: createMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMessageRequestBody'

      responses:
        '200':
          description: OK

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '500':
          description: Internal Server Error

components:
  schemas:
    CreateMessageRequestBody:
      type: object
      required:
        - userId
        - category
        - country
        - content
      properties:
        userId:
          type: string
        category:
          type: string
        country:
          type: string
        content:
          type: string
