openapi: 3.0.0
info:
  title: EU Talent API
  version: 1.0.0
paths:
  /api/get-quiz-question:
    get:
      summary: Get a single question
      operationId: getQuizQuestion

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetQuizQuestionResponseBody'

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '500':
          description: Internal Server Error

components:
  schemas:
    GetQuizQuestionResponseBody:
      type: object
      properties:
        id:
          type: integer

        createdAt:
          type: string
