openapi: 3.0.0
info:
  title: EU Talent API
  version: 1.0.0
paths:
  /api/get-messages:
    get:
      summary: Get all messages of a category and county
      operationId: getMessages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMessagesRequestBody'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMessagesResponseBody'

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '500':
          description: Internal Server Error

components:
  schemas:
    GetMessagesRequestBody:
      type: object
      required:
        - userId
        - category
        - country
      properties:
        userId:
          type: string
        category:
          type: string
        country:
          type: string

    GetMessagesResponseBody:
      type: object
      properties:
        id:
          type: integer
        category:
          type: string
        country:
          type: string
        isFromCurrentUser:
          type: boolean
        createdAt:
          type: string
